import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dars qo'shish",
  description: "Generated by create next app",
};

const layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div>{children}</div>
  )
}

export default layout