import type { Metadata } from "next";
import "./globals.css";
import SideBar from "./components/SideBar";
import { ToastContainer } from "react-toastify";
import AuthWrapper from "./AuthWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`pl-96`}
      >
        <AuthWrapper>
          <SideBar />
          <ToastContainer />
          {children}
        </AuthWrapper>
      </body>
    </html>
  );
}
